# TODO: Add license header here


"""CKConv Multi-Head (long-convolution with dense within-head mixing) for ND signals.

This module implements a multi-head variant of CKConv where each head performs
dense [head_dim x head_dim] channel mixing, similar to multi-head attention but
for convolutions.

Key difference from standard CKConvND (depthwise):
- CKConvND: Each channel convolved independently (depthwise)
- CKConvMultiheadND: Dense channel mixing within each head

This enables cross-channel feature learning while maintaining computational
efficiency through head isolation.
"""

import math
from typing import Literal

import torch
from einops import rearrange

from nvsubquadratic.lazy_config import LazyConfig, instantiate
from nvsubquadratic.ops.fftconv_multihead import (
    fftconv2d_multihead_bhl,
    fftconv2d_multihead_circular_bhl,
)


class CKConvMultiheadND(torch.nn.Module):
    """CKConv with multi-head dense channel mixing for 2D signals.

    Each head performs dense [head_dim x head_dim] convolution, enabling
    cross-channel feature learning within heads while keeping heads isolated.

    The kernel is generated by a SIREN network that outputs
    [num_heads * head_dim * head_dim] values per spatial position.
    """

    def __init__(
        self,
        data_dim: int,
        hidden_dim: int,
        num_heads: int,
        kernel_cfg: LazyConfig,
        mask_cfg: LazyConfig,
        grid_type: Literal["double", "single"],
        fft_padding: Literal["zero", "circular"],
    ):
        """Initialize CKConvMultiheadND.

        Args:
            data_dim: Dimension of input data (currently only 2D supported).
            hidden_dim: Hidden dimension (must be divisible by num_heads).
            num_heads: Number of heads for channel grouping.
            kernel_cfg: LazyConfig for the SIREN kernel network.
                The kernel should output [num_heads * head_dim * head_dim] values.
            mask_cfg: LazyConfig for the mask (typically Identity).
            grid_type: Grid type for kernel generation ("single" or "double").
            fft_padding: FFT padding mode ("zero" or "circular").
        """
        assert data_dim == 2, f"CKConvMultiheadND currently only supports 2D. Got {data_dim}D."
        assert hidden_dim % num_heads == 0, f"hidden_dim ({hidden_dim}) must be divisible by num_heads ({num_heads})"
        assert grid_type in ["double", "single"], f"Invalid grid_type: {grid_type}"
        assert fft_padding in ["zero", "circular"], f"Invalid fft_padding: {fft_padding}"

        if fft_padding == "circular":
            assert grid_type == "single", (
                "fft_padding='circular' requires grid_type='single' (kernel size equals input size)."
            )

        super().__init__()
        self.data_dim = data_dim
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads
        self.fft_padding = fft_padding
        self.grid_type = grid_type

        # Construct kernel (SIREN) and mask
        self.kernel = instantiate(kernel_cfg)
        self.mask = instantiate(mask_cfg)

        # Apply 1/sqrt(head_dim) scaling to kernel output for variance control.
        # Multi-head dense conv sums over head_dim terms, so variance grows by head_dim
        # without this correction. Similar to attention's 1/sqrt(d_k) scaling.
        with torch.no_grad():
            self.kernel.out_linear.weight.data *= math.sqrt(1.0 / self.head_dim)

        # Shortcut parameter for residual connection
        self.shortcut = torch.nn.Parameter(torch.empty(hidden_dim, dtype=torch.float32))
        bounds = math.sqrt(1.0 / hidden_dim)
        self.shortcut.data.uniform_(-bounds, bounds)

        # Select FFT convolution function
        if fft_padding == "circular":
            self.fftconv_fn = fftconv2d_multihead_circular_bhl
        else:
            self.fftconv_fn = fftconv2d_multihead_bhl

    def extra_repr(self) -> str:
        """Return extra representation string for the module."""
        return (
            f"data_dim={self.data_dim}, hidden_dim={self.hidden_dim}, "
            f"num_heads={self.num_heads}, head_dim={self.head_dim}, "
            f"fft_padding={self.fft_padding!r}, grid_type={self.grid_type!r}"
        )

    def apply_convolution(self, x: torch.Tensor, conv_kernel: torch.Tensor, shortcut: torch.Tensor) -> torch.Tensor:
        """Apply the multi-head convolution.

        Args:
            x: Input tensor [B, num_heads, head_dim, H, W], float32
            conv_kernel: Kernel [num_heads, head_dim, head_dim, K_x, K_y], float32
            shortcut: Shortcut tensor [hidden_dim], float32

        Returns:
            Output tensor [B, num_heads, head_dim, H, W]
        """
        x_dtype = x.dtype
        out = self.fftconv_fn(
            x.to(torch.float32),
            conv_kernel.to(torch.float32),
            shortcut.to(torch.float32),
        )
        return out.to(x_dtype)

    def forward(
        self, x: torch.Tensor, is_bhl_input: bool = False, cp_group: torch.distributed.ProcessGroup = None
    ) -> torch.Tensor:
        """Forward pass of CKConvMultiheadND.

        Args:
            x: Input tensor. Shape depends on is_bhl_input:
               - is_bhl_input=False: [B, H, W, hidden_dim] (BLH format)
               - is_bhl_input=True: [B, hidden_dim, H, W] (BHL format)
            is_bhl_input: Whether input is in BHL format.
            cp_group: Context parallel process group (not supported for multi-head).

        Returns:
            Output tensor in same format as input.
        """
        if cp_group is not None and cp_group.size() > 1:
            raise NotImplementedError("Context parallelism not yet supported for CKConvMultiheadND")

        # Get spatial dimensions
        if is_bhl_input:
            B, C, H, W = x.shape
            # Reshape to [B, num_heads, head_dim, H, W]
            x_heads = x.view(B, self.num_heads, self.head_dim, H, W)
        else:
            B, H, W, C = x.shape
            # Reshape to [B, num_heads, head_dim, H, W]
            x_heads = rearrange(x, "b h w (n d) -> b n d h w", n=self.num_heads, d=self.head_dim)

        spatial_dims = (H, W)

        # Determine grid lengths for kernel generation
        if self.grid_type == "single":
            grid_lens = [(s + 1) // 2 for s in spatial_dims]
        else:  # "double"
            grid_lens = spatial_dims

        # Generate kernel from SIREN
        # Output: [1, *spatial, num_heads * head_dim * head_dim]
        conv_kernel_flat, grid = self.kernel(grid_lens)

        # Apply mask if not identity
        if not isinstance(self.mask, torch.nn.Identity):
            conv_kernel_flat = self.mask(grid=grid, x=conv_kernel_flat)

        # Reshape kernel: [1, K_x, K_y, num_heads * head_dim²] -> [num_heads, head_dim, head_dim, K_x, K_y]
        K_x, K_y = conv_kernel_flat.shape[1], conv_kernel_flat.shape[2]
        conv_kernel = conv_kernel_flat.view(K_x, K_y, self.num_heads, self.head_dim, self.head_dim)
        conv_kernel = conv_kernel.permute(2, 3, 4, 0, 1).contiguous()  # [num_heads, head_dim, head_dim, K_x, K_y]

        # Cache kernel stats for debugging (only when enabled by LayerStatsCallback)
        if getattr(self, "_cache_debug_stats", False):
            with torch.no_grad():
                self._debug_stats = {
                    "norm": conv_kernel.norm().item(),
                    "max_abs": conv_kernel.abs().max().item(),
                }

        # Apply multi-head convolution
        out_heads = self.apply_convolution(x_heads, conv_kernel, self.shortcut)

        # Reshape back to original format
        if is_bhl_input:
            # [B, num_heads, head_dim, H, W] -> [B, hidden_dim, H, W]
            out = out_heads.view(B, self.hidden_dim, H, W)
        else:
            # [B, num_heads, head_dim, H, W] -> [B, H, W, hidden_dim]
            out = rearrange(out_heads, "b n d h w -> b h w (n d)")

        return out
