# TODO: Add license header here


"""CKConv Multi-Head (long-convolution with dense within-head mixing) for ND signals.

This module implements a multi-head variant of CKConv where each head performs
dense [head_dim x head_dim] channel mixing, similar to multi-head attention but
for convolutions.

Key difference from standard CKConvND (depthwise):
- CKConvND: Each channel convolved independently (depthwise)
- CKConvMultiheadND: Dense channel mixing within each head

Supports an optional low-rank kernel factorization (``kernel_rank``) that
decomposes the full [head_dim x head_dim] kernel into two [head_dim x rank]
factors U and V, reducing SIREN output, FFT conv cost, and memory by
approximately ``2*rank / head_dim``.

This enables cross-channel feature learning while maintaining computational
efficiency through head isolation.
"""

import math
from typing import Literal

import torch
from einops import rearrange

from nvsubquadratic.lazy_config import LazyConfig, instantiate
from nvsubquadratic.ops.fftconv_multihead import (
    fftconv2d_multihead_bhl,
    fftconv2d_multihead_circular_bhl,
    fftconv2d_multihead_lowrank_bhl,
    fftconv2d_multihead_lowrank_circular_bhl,
)


class CKConvMultiheadND(torch.nn.Module):
    """CKConv with multi-head dense channel mixing for 2D signals.

    Each head performs dense [head_dim x head_dim] convolution, enabling
    cross-channel feature learning within heads while keeping heads isolated.

    The kernel is generated by a SIREN network that outputs
    [num_heads * head_dim * head_dim] values per spatial position (full-rank),
    or [num_heads * 2 * kernel_rank * head_dim] values (low-rank).
    """

    def __init__(
        self,
        data_dim: int,
        hidden_dim: int,
        num_heads: int,
        kernel_cfg: LazyConfig,
        mask_cfg: LazyConfig,
        grid_type: Literal["double", "single"],
        fft_padding: Literal["zero", "circular"],
        kernel_rank: int | None = None,
    ):
        """Initialize CKConvMultiheadND.

        Args:
            data_dim: Dimension of input data (currently only 2D supported).
            hidden_dim: Hidden dimension (must be divisible by num_heads).
            num_heads: Number of heads for channel grouping.
            kernel_cfg: LazyConfig for the SIREN kernel network.
                Full-rank: outputs [num_heads * head_dim * head_dim] values.
                Low-rank: outputs [num_heads * 2 * kernel_rank * head_dim] values.
            mask_cfg: LazyConfig for the mask (typically Identity).
            grid_type: Grid type for kernel generation ("single" or "double").
            fft_padding: FFT padding mode ("zero" or "circular").
            kernel_rank: Rank for low-rank kernel factorization. When None (default),
                uses full-rank [head_dim x head_dim] kernels. When set, factorizes
                into U @ V^T where U,V have shape [..., head_dim, rank]. Reduces
                SIREN output by ``2*rank / head_dim`` and FFT conv cost similarly.
        """
        assert data_dim == 2, f"CKConvMultiheadND currently only supports 2D. Got {data_dim}D."
        assert hidden_dim % num_heads == 0, f"hidden_dim ({hidden_dim}) must be divisible by num_heads ({num_heads})"
        assert grid_type in ["double", "single"], f"Invalid grid_type: {grid_type}"
        assert fft_padding in ["zero", "circular"], f"Invalid fft_padding: {fft_padding}"

        if fft_padding == "circular":
            assert grid_type == "single", (
                "fft_padding='circular' requires grid_type='single' (kernel size equals input size)."
            )

        super().__init__()
        self.data_dim = data_dim
        self.hidden_dim = hidden_dim
        self.num_heads = num_heads
        self.head_dim = hidden_dim // num_heads
        self.fft_padding = fft_padding
        self.grid_type = grid_type
        self.kernel_rank = kernel_rank

        # Construct kernel (SIREN) and mask
        self.kernel = instantiate(kernel_cfg)
        self.mask = instantiate(mask_cfg)

        # Apply output scaling for variance control.
        # Full-rank: conv sums over head_dim terms → scale by 1/sqrt(head_dim).
        # Low-rank: conv sums over head_dim then rank → scale by 1/(head_dim * rank)^{1/4}
        #   so that each factor (U, V) has the right variance independently.
        with torch.no_grad():
            if kernel_rank is not None:
                self.kernel.out_linear.weight.data *= (1.0 / (self.head_dim * kernel_rank)) ** 0.25
            else:
                self.kernel.out_linear.weight.data *= math.sqrt(1.0 / self.head_dim)

        # Shortcut parameter for residual connection
        self.shortcut = torch.nn.Parameter(torch.empty(hidden_dim, dtype=torch.float32))
        bounds = math.sqrt(1.0 / hidden_dim)
        self.shortcut.data.uniform_(-bounds, bounds)

        # Select FFT convolution function
        if kernel_rank is not None:
            if fft_padding == "circular":
                self.fftconv_fn = fftconv2d_multihead_lowrank_circular_bhl
            else:
                self.fftconv_fn = fftconv2d_multihead_lowrank_bhl
        else:
            if fft_padding == "circular":
                self.fftconv_fn = fftconv2d_multihead_circular_bhl
            else:
                self.fftconv_fn = fftconv2d_multihead_bhl

    def extra_repr(self) -> str:
        """Return extra representation string for the module."""
        parts = (
            f"data_dim={self.data_dim}, hidden_dim={self.hidden_dim}, "
            f"num_heads={self.num_heads}, head_dim={self.head_dim}, "
            f"fft_padding={self.fft_padding!r}, grid_type={self.grid_type!r}"
        )
        if self.kernel_rank is not None:
            parts += f", kernel_rank={self.kernel_rank}"
        return parts

    def _reshape_lowrank_kernel(self, conv_kernel_flat: torch.Tensor, K_x: int, K_y: int, B: int | None = None):
        """Reshape SIREN output into U and V low-rank factors.

        Args:
            conv_kernel_flat: [..., K_x, K_y, num_heads * 2 * rank * head_dim]
            K_x: Spatial kernel height dimension.
            K_y: Spatial kernel width dimension.
            B: Batch size (for FiLM-batched kernels), or None for unbatched.

        Returns:
            (kernel_u, kernel_v) tuple:
                Unbatched: U [num_heads, head_dim, rank, K_x, K_y],
                           V [num_heads, rank, head_dim, K_x, K_y]
                Batched:   U [B, num_heads, head_dim, rank, K_x, K_y],
                           V [B, num_heads, rank, head_dim, K_x, K_y]
        """
        rank = self.kernel_rank
        head_dim = self.head_dim
        num_heads = self.num_heads

        if B is not None:
            # FiLM-batched: [B, K_x, K_y, num_heads * 2 * rank * head_dim]
            # -> [B, K_x, K_y, num_heads, 2, rank, head_dim]
            reshaped = conv_kernel_flat.view(B, K_x, K_y, num_heads, 2, rank, head_dim)
            # After [:, :, :, :, idx, :, :] -> [B, K_x, K_y, num_heads, rank, head_dim]
            # U target: [B, num_heads, head_dim, rank, K_x, K_y]
            kernel_u = reshaped[:, :, :, :, 0, :, :].permute(0, 3, 5, 4, 1, 2).contiguous()
            # V target: [B, num_heads, rank, head_dim, K_x, K_y]
            kernel_v = reshaped[:, :, :, :, 1, :, :].permute(0, 3, 4, 5, 1, 2).contiguous()
        else:
            # Unbatched: [1, K_x, K_y, num_heads * 2 * rank * head_dim]
            # -> [K_x, K_y, num_heads, 2, rank, head_dim]
            reshaped = conv_kernel_flat.view(K_x, K_y, num_heads, 2, rank, head_dim)
            # After [:, :, :, idx, :, :] -> [K_x, K_y, num_heads, rank, head_dim]
            # U target: [num_heads, head_dim, rank, K_x, K_y]
            kernel_u = reshaped[:, :, :, 0, :, :].permute(2, 4, 3, 0, 1).contiguous()
            # V target: [num_heads, rank, head_dim, K_x, K_y]
            kernel_v = reshaped[:, :, :, 1, :, :].permute(2, 3, 4, 0, 1).contiguous()

        return kernel_u, kernel_v

    def apply_convolution(self, x: torch.Tensor, conv_kernel: torch.Tensor, shortcut: torch.Tensor) -> torch.Tensor:
        """Apply the multi-head convolution (full-rank).

        Args:
            x: Input tensor [B, num_heads, head_dim, H, W], float32
            conv_kernel: Kernel [num_heads, head_dim, head_dim, K_x, K_y], float32
            shortcut: Shortcut tensor [hidden_dim], float32

        Returns:
            Output tensor [B, num_heads, head_dim, H, W]
        """
        x_dtype = x.dtype
        out = self.fftconv_fn(
            x.to(torch.float32),
            conv_kernel.to(torch.float32),
            shortcut.to(torch.float32),
        )
        return out.to(x_dtype)

    def apply_convolution_lowrank(
        self, x: torch.Tensor, kernel_u: torch.Tensor, kernel_v: torch.Tensor, shortcut: torch.Tensor
    ) -> torch.Tensor:
        """Apply the multi-head convolution (low-rank).

        Args:
            x: Input tensor [B, num_heads, head_dim, H, W]
            kernel_u: U factor [num_heads, head_dim, rank, K_x, K_y]
            kernel_v: V factor [num_heads, rank, head_dim, K_x, K_y]
            shortcut: Shortcut tensor [hidden_dim]

        Returns:
            Output tensor [B, num_heads, head_dim, H, W]
        """
        x_dtype = x.dtype
        out = self.fftconv_fn(
            x.to(torch.float32),
            kernel_u.to(torch.float32),
            kernel_v.to(torch.float32),
            shortcut.to(torch.float32),
        )
        return out.to(x_dtype)

    def apply_convolution_batched(
        self, x: torch.Tensor, conv_kernel: torch.Tensor, shortcut: torch.Tensor
    ) -> torch.Tensor:
        """Apply multi-head convolution with per-sample (batched) kernels (full-rank).

        When FiLM conditioning is used, each sample in the batch has its own kernel.
        We perform the FFT convolution with a batched einsum.

        Args:
            x: Input tensor [B, num_heads, head_dim, H, W], float32
            conv_kernel: Kernel [B, num_heads, head_dim, head_dim, K_x, K_y], float32
            shortcut: Shortcut tensor [hidden_dim], float32

        Returns:
            Output tensor [B, num_heads, head_dim, H, W]
        """
        x = x.to(torch.float32)
        conv_kernel = conv_kernel.to(torch.float32)
        shortcut = shortcut.to(torch.float32)

        _B, num_heads, head_dim, H, W = x.shape
        K_x, K_y = conv_kernel.shape[-2], conv_kernel.shape[-1]

        fft_h = min(H + (K_x + 1) // 2, 2 * H)
        fft_w = min(W + (K_y + 1) // 2, 2 * W)

        x_fft = torch.fft.rfft2(x, s=(fft_h, fft_w))
        k_fft = torch.fft.rfft2(conv_kernel, s=(fft_h, fft_w))

        # Batched dense conv: both x and kernel have batch dim
        out_fft = torch.einsum("bnihw,bnoihw->bnohw", x_fft, k_fft)

        crop_h = K_x // 2
        crop_w = K_y // 2
        out_full = torch.fft.irfft2(out_fft, s=(fft_h, fft_w))
        out = out_full[..., crop_h : crop_h + H, crop_w : crop_w + W]

        shortcut_reshaped = shortcut.view(1, num_heads, head_dim, 1, 1)
        out = out + x * shortcut_reshaped

        return out

    def apply_convolution_batched_lowrank(
        self,
        x: torch.Tensor,
        kernel_u: torch.Tensor,
        kernel_v: torch.Tensor,
        shortcut: torch.Tensor,
    ) -> torch.Tensor:
        """Apply multi-head low-rank convolution with per-sample (batched) kernels.

        Args:
            x: Input tensor [B, num_heads, head_dim, H, W]
            kernel_u: U factor [B, num_heads, head_dim, rank, K_x, K_y]
            kernel_v: V factor [B, num_heads, rank, head_dim, K_x, K_y]
            shortcut: Shortcut tensor [hidden_dim]

        Returns:
            Output tensor [B, num_heads, head_dim, H, W]
        """
        x = x.to(torch.float32)
        kernel_u = kernel_u.to(torch.float32)
        kernel_v = kernel_v.to(torch.float32)
        shortcut = shortcut.to(torch.float32)

        _B, num_heads, head_dim, H, W = x.shape
        K_x, K_y = kernel_u.shape[-2], kernel_u.shape[-1]

        fft_h = min(H + (K_x + 1) // 2, 2 * H)
        fft_w = min(W + (K_y + 1) // 2, 2 * W)

        x_fft = torch.fft.rfft2(x, s=(fft_h, fft_w))
        u_fft = torch.fft.rfft2(kernel_u, s=(fft_h, fft_w))
        v_fft = torch.fft.rfft2(kernel_v, s=(fft_h, fft_w))

        # Two-step low-rank conv (avoids materializing full [head_dim x head_dim] K_fft)
        # Step 1: z = V @ x — contract over head_dim_in
        z_fft = torch.einsum("bnihw,bnrihw->bnrhw", x_fft, v_fft)
        # Step 2: y = U @ z — contract over rank
        out_fft = torch.einsum("bnrhw,bnorhw->bnohw", z_fft, u_fft)

        crop_h = K_x // 2
        crop_w = K_y // 2
        out_full = torch.fft.irfft2(out_fft, s=(fft_h, fft_w))
        out = out_full[..., crop_h : crop_h + H, crop_w : crop_w + W]

        shortcut_reshaped = shortcut.view(1, num_heads, head_dim, 1, 1)
        out = out + x * shortcut_reshaped

        return out

    def forward(
        self,
        x: torch.Tensor,
        is_bhl_input: bool = False,
        cp_group: torch.distributed.ProcessGroup = None,
        **mixer_kwargs,
    ) -> torch.Tensor:
        """Forward pass of CKConvMultiheadND.

        Args:
            x: Input tensor. Shape depends on is_bhl_input:
               - is_bhl_input=False: [B, H, W, hidden_dim] (BLH format)
               - is_bhl_input=True: [B, hidden_dim, H, W] (BHL format)
            is_bhl_input: Whether input is in BHL format.
            cp_group: Context parallel process group (not supported for multi-head).
            **mixer_kwargs: Additional keyword arguments forwarded to the kernel generator
                (e.g. ``conditioning`` for FiLM-enabled SIRENKernelND).

        Returns:
            Output tensor in same format as input.
        """
        if cp_group is not None and cp_group.size() > 1:
            raise NotImplementedError("Context parallelism not yet supported for CKConvMultiheadND")

        # Get spatial dimensions
        if is_bhl_input:
            B, _C, H, W = x.shape
            # Reshape to [B, num_heads, head_dim, H, W]
            x_heads = x.view(B, self.num_heads, self.head_dim, H, W)
        else:
            B, H, W, _C = x.shape
            # Reshape to [B, num_heads, head_dim, H, W]
            x_heads = rearrange(x, "b h w (n d) -> b n d h w", n=self.num_heads, d=self.head_dim)

        spatial_dims = (H, W)

        # Determine grid lengths for kernel generation
        if self.grid_type == "single":
            grid_lens = [(s + 1) // 2 for s in spatial_dims]
        else:  # "double"
            grid_lens = spatial_dims

        # Generate kernel from SIREN (pass conditioning if available for FiLM-enabled kernels)
        # Full-rank output: [1, *spatial, num_heads * head_dim * head_dim]
        # Low-rank output: [1, *spatial, num_heads * 2 * rank * head_dim]
        conditioning = mixer_kwargs.get("conditioning", None)
        conv_kernel_flat, grid = self.kernel(grid_lens, conditioning=conditioning)

        # Apply mask if not identity
        if not isinstance(self.mask, torch.nn.Identity):
            conv_kernel_flat = self.mask(grid=grid, x=conv_kernel_flat)

        K_x, K_y = conv_kernel_flat.shape[-3], conv_kernel_flat.shape[-2]
        batched_kernel = conv_kernel_flat.shape[0] > 1

        if self.kernel_rank is not None:
            # Low-rank path: reshape SIREN output into U and V factors
            kernel_u, kernel_v = self._reshape_lowrank_kernel(
                conv_kernel_flat, K_x, K_y, B=B if batched_kernel else None
            )

            # Cache kernel stats for debugging
            if getattr(self, "_cache_debug_stats", False):
                with torch.no_grad():
                    self._debug_stats = {
                        "norm_u": kernel_u.norm().item(),
                        "norm_v": kernel_v.norm().item(),
                        "max_abs_u": kernel_u.abs().max().item(),
                        "max_abs_v": kernel_v.abs().max().item(),
                    }

            if batched_kernel:
                out_heads = self.apply_convolution_batched_lowrank(x_heads, kernel_u, kernel_v, self.shortcut)
            else:
                out_heads = self.apply_convolution_lowrank(x_heads, kernel_u, kernel_v, self.shortcut)
        else:
            # Full-rank path: reshape SIREN output into [num_heads, head_dim, head_dim, K_x, K_y]
            if batched_kernel:
                conv_kernel = conv_kernel_flat.view(B, K_x, K_y, self.num_heads, self.head_dim, self.head_dim)
                conv_kernel = conv_kernel.permute(0, 3, 4, 5, 1, 2).contiguous()
            else:
                conv_kernel = conv_kernel_flat.view(K_x, K_y, self.num_heads, self.head_dim, self.head_dim)
                conv_kernel = conv_kernel.permute(2, 3, 4, 0, 1).contiguous()

            # Cache kernel stats for debugging
            if getattr(self, "_cache_debug_stats", False):
                with torch.no_grad():
                    self._debug_stats = {
                        "norm": conv_kernel.norm().item(),
                        "max_abs": conv_kernel.abs().max().item(),
                    }

            if batched_kernel:
                out_heads = self.apply_convolution_batched(x_heads, conv_kernel, self.shortcut)
            else:
                out_heads = self.apply_convolution(x_heads, conv_kernel, self.shortcut)

        # Reshape back to original format
        if is_bhl_input:
            # [B, num_heads, head_dim, H, W] -> [B, hidden_dim, H, W]
            out = out_heads.reshape(B, self.hidden_dim, H, W)
        else:
            # [B, num_heads, head_dim, H, W] -> [B, H, W, hidden_dim]
            out = rearrange(out_heads, "b n d h w -> b h w (n d)")

        return out
