"""Spectral masking operations for learnable downsampling and upsampling.

This module implements DiffStride-style spectral masking for differentiable
downsampling/upsampling in the frequency domain. See: https://arxiv.org/abs/2202.01653

The key idea is to apply a soft Gaussian mask in the Fourier domain to
attenuate high frequencies before cropping (downsampling) or after padding
(upsampling), enabling gradient flow through the resampling operation.
"""

import torch


def spectral_downsampling2d_bhl(
    x: torch.Tensor,
    spectral_mask: torch.Tensor,
) -> torch.Tensor:
    """Apply spectral masking for differentiable 2D downsampling.

    Performs learnable downsampling by:
    1. Zero-padding input to avoid circular convolution artifacts
    2. Transforming input to frequency domain via rfft2
    3. Cropping to keep low frequencies (determined by mask size)
    4. Applying a soft Gaussian mask for smooth attenuation and gradient flow
    5. Transforming back to spatial domain via irfft2
    6. Cropping the valid (non-wrapped) region

    This implements the DiffStride approach where the mask enables learning
    the effective stride/downsampling factor through backpropagation.

    Args:
        x: Input tensor of shape (B, C, H, W) in BHL (Batch, Hidden, Length) format.
        spectral_mask: Gaussian mask of shape (1, C, sM_x, sM_y) where:
            - sM_x determines output height (target_H = sM_x)
            - sM_y determines output width (target_W = 2 * (sM_y - 1))
            - The mask should have peak=1 at center (DC frequency position)
            - Generated by SpectralGaussianMaskND with coords centered at 0

    Returns:
        Downsampled tensor of shape (B, C, target_H, target_W).

    Note:
        The mask is internally shifted via ifftshift to align with the FFT layout
        where DC is at index 0 after cropping. The output is normalized by the
        area ratio to preserve signal amplitude.

        To avoid circular convolution artifacts (border smearing), the input is
        zero-padded to 1.5x its size before the FFT. This ensures the low-pass
        filtering doesn't wrap around the borders.

    Example:
        >>> from nvsubquadratic.modules.masks_nd import SpectralGaussianMaskND
        >>> mask_module = SpectralGaussianMaskND(data_dim=2, clip_value=0.1, init_stride_value=2.0)
        >>> x = torch.randn(1, 64, 256, 256)
        >>> spectral_mask = mask_module((256, 256)).unsqueeze(1).expand(-1, 64, -1, -1)
        >>> y = spectral_downsampling2d_bhl(x, spectral_mask)  # shape: (1, 64, 128, 128)
    """
    _, _, sM_x, sM_y = spectral_mask.shape
    target_H, target_W = sM_x, 2 * (sM_y - 1)
    orig_H, orig_W = x.shape[2], x.shape[3]

    # Zero-pad to 1.5x size to avoid circular convolution artifacts.
    # This ensures the implied low-pass filter doesn't wrap around borders.
    # 1.5x is sufficient because:
    #   - The filter's spatial extent is ~2*stride samples (main sinc lobe)
    #   - The Gaussian mask smooths the cutoff, further localizing the filter
    #   - 0.5*orig_size padding captures main lobe + several side lobes
    # Note: 2x would be more conservative but uses more memory/compute.
    pad_factor = 1.5
    padded_H = int(pad_factor * orig_H)
    padded_W = int(pad_factor * orig_W)

    # FFT with zero-padding (rfft2 will zero-pad when s > input size)
    fft_x = torch.fft.rfft2(x, s=(padded_H, padded_W), dim=(2, 3))

    # Scale crop sizes by pad_factor to keep the same physical frequencies
    # For height: pad_factor * original crop size
    # For width (rfft): account for the +1 Nyquist bin
    crop_sM_x = int(pad_factor * sM_x)
    crop_sM_y = int(pad_factor * (sM_y - 1)) + 1

    # Center crop to keep low frequencies
    # For dim 2 (height): use fftshift to center DC, crop, then ifftshift
    # For dim 3 (width): just crop from start (rfft only has positive frequencies)
    H_freq = fft_x.shape[2]  # = padded_H
    fft_x_shifted = torch.fft.fftshift(fft_x, dim=2)
    start_x = (H_freq - crop_sM_x) // 2
    fft_x_cropped = fft_x_shifted[:, :, start_x : start_x + crop_sM_x, :crop_sM_y]
    fft_x_cropped = torch.fft.ifftshift(fft_x_cropped, dim=2)

    # Resize the spectral mask to match the padded crop size
    # The mask is smooth (Gaussian), so bilinear interpolation preserves its properties
    spectral_mask_resized = torch.nn.functional.interpolate(
        spectral_mask,
        size=(crop_sM_x, crop_sM_y),
        mode="bilinear",
        align_corners=True,
    )

    # Apply soft spectral mask (for gradient flow)
    # The mask is generated with peak at center (coords centered at 0), but after
    # ifftshift above, DC is at corner. So we need to ifftshift the mask to align.
    spectral_mask_aligned = torch.fft.ifftshift(spectral_mask_resized, dim=2)
    fft_x_masked = fft_x_cropped * spectral_mask_aligned

    # Inverse FFT to get padded downsampled output (1.5x target size)
    padded_target_H = int(pad_factor * target_H)
    padded_target_W = int(pad_factor * target_W)
    y_padded = torch.fft.irfft2(fft_x_masked, s=(padded_target_H, padded_target_W), dim=(2, 3))

    # Crop to target size - keep the first target_H x target_W
    # This is the valid, non-wrapped region corresponding to the original input
    y = y_padded[:, :, :target_H, :target_W]

    # Normalize by the area ratio to preserve signal amplitude
    # The normalization accounts for the padded domain sizes
    normalization = (padded_target_H * padded_target_W) / (padded_H * padded_W)
    y = y * normalization
    return y


def spectral_upsampling2d_bhl(
    x: torch.Tensor,
    target_shape: tuple[int, int],
    spectral_mask: torch.Tensor | None = None,
) -> torch.Tensor:
    """Apply spectral zero-padding for differentiable 2D upsampling.

    Performs learnable upsampling by:
    1. Zero-padding input to avoid circular convolution artifacts
    2. Transforming input to frequency domain via rfft2
    3. Applying a soft Gaussian mask for smooth attenuation (optional)
    4. Zero-padding to target frequency size (high frequencies set to zero)
    5. Transforming back to spatial domain via irfft2
    6. Cropping the valid (non-wrapped) region

    This is the inverse of spectral_downsampling2d_bhl and implements ideal
    (sinc) interpolation when no mask is applied, or smooth interpolation
    when a Gaussian mask is used.

    Args:
        x: Input tensor of shape (B, C, H, W) in BHL (Batch, Hidden, Length) format.
        target_shape: Target spatial shape (target_H, target_W) for the upsampled output.
        spectral_mask: Optional Gaussian mask of shape (1, C, sM_x, sM_y) where:
            - sM_x = H (input height, matches frequency extent in dim 2)
            - sM_y = W // 2 + 1 (input rfft width)
            - The mask should have peak=1 at center (DC frequency position)
            - Generated by SpectralGaussianMaskND with coords centered at 0
            If None, no soft masking is applied (ideal sinc interpolation).

    Returns:
        Upsampled tensor of shape (B, C, target_H, target_W).

    Note:
        Zero-padding in the frequency domain is equivalent to ideal (sinc)
        interpolation in the spatial domain. The Gaussian mask provides a
        smooth rolloff that helps with gradient flow and reduces ringing.

        To avoid circular convolution artifacts (border smearing), the input is
        zero-padded to 1.5x its size before the FFT. This ensures the sinc
        interpolation doesn't wrap around the borders.

    Example:
        >>> x_small = torch.randn(1, 64, 64, 64)
        >>> y = spectral_upsampling2d_bhl(x_small, target_shape=(256, 256))
        >>> print(y.shape)  # (1, 64, 256, 256)
    """
    B, C, orig_H, orig_W = x.shape
    target_H, target_W = target_shape

    assert target_H >= orig_H, f"target_H ({target_H}) must be >= input height ({orig_H})"
    assert target_W >= orig_W, f"target_W ({target_W}) must be >= input width ({orig_W})"

    # Zero-pad to 1.5x size to avoid circular convolution artifacts.
    # See spectral_downsampling2d_bhl for detailed explanation.
    pad_factor = 1.5
    padded_orig_H = int(pad_factor * orig_H)
    padded_orig_W = int(pad_factor * orig_W)

    # FFT with zero-padding
    fft_x = torch.fft.rfft2(x, s=(padded_orig_H, padded_orig_W), dim=(2, 3))
    # Shape: (B, C, padded_orig_H, padded_orig_W // 2 + 1)

    # Apply soft spectral mask before padding (optional, for smooth interpolation)
    if spectral_mask is not None:
        _, _, sM_x, sM_y = spectral_mask.shape
        assert sM_x == orig_H, f"Mask height ({sM_x}) must match input height ({orig_H})"
        # Resize mask to match padded FFT size
        padded_sM_x = int(pad_factor * sM_x)
        padded_sM_y = int(pad_factor * (sM_y - 1)) + 1
        spectral_mask_resized = torch.nn.functional.interpolate(
            spectral_mask,
            size=(padded_sM_x, padded_sM_y),
            mode="bilinear",
            align_corners=True,
        )
        # Align mask with FFT layout (DC at corner)
        spectral_mask_aligned = torch.fft.ifftshift(spectral_mask_resized, dim=2)
        fft_x = fft_x * spectral_mask_aligned

    # Zero-pad to target frequency size (accounting for padded domain)
    # For the padded domain, target size is also scaled by pad_factor
    padded_target_H = int(pad_factor * target_H)
    padded_target_W = int(pad_factor * target_W)
    target_freq_H = padded_target_H
    target_freq_W = padded_target_W // 2 + 1

    # Shift to center DC, pad, then unshift
    fft_x_shifted = torch.fft.fftshift(fft_x, dim=2)

    # Create zero-padded tensor
    fft_x_padded = torch.zeros(B, C, target_freq_H, target_freq_W, dtype=fft_x.dtype, device=fft_x.device)

    # Calculate padding offsets (center the small FFT in the larger one)
    pad_start_H = (target_freq_H - padded_orig_H) // 2
    _pad_start_W = 0  # For rfft, we only have positive frequencies, so pad at the end

    # Place the original (shifted) FFT in the center
    fft_x_padded[:, :, pad_start_H : pad_start_H + padded_orig_H, : fft_x.shape[3]] = fft_x_shifted

    # Unshift back to standard FFT layout
    fft_x_padded = torch.fft.ifftshift(fft_x_padded, dim=2)

    # Inverse FFT to get padded upsampled output
    y_padded = torch.fft.irfft2(fft_x_padded, s=(padded_target_H, padded_target_W), dim=(2, 3))

    # Crop to target size - keep the first target_H x target_W
    # This is the valid, non-wrapped region
    y = y_padded[:, :, :target_H, :target_W]

    # Normalize to preserve signal amplitude
    # The normalization accounts for the padded domain sizes
    normalization = (padded_target_H * padded_target_W) / (padded_orig_H * padded_orig_W)
    y = y * normalization

    return y
